# -*- coding: utf-8 -*-
"""
Questions 1 to 25 (Easy Fundamentals & Core Tracing)
Difficulty: All 25 are Easy
Styles: Output Prediction, Logic Tracing, Debugging, Array Tracing, String Tracing, Bitwise, Scenario
"""

def get_q1_to_25():
    return [
        {
            "id": 1,
            "question": "What will be the output of the following pseudocode?",
            "pseudocode": "Integer a, b, c\nSet a = 14, b = 4\nSet c = a / b + a % b\nPrint c",
            "question_type": "Output Prediction",
            "topic": "Programming Fundamentals",
            "concept": "Integer division and modulo operator",
            "difficulty": "Easy",
            "options": ["5", "3", "5.5", "6"],
            "correct_answer": "5",
            "correct_option_index": 0,
            "explanation": "In pseudocode, integer division between two integers truncates the decimal part: 14 / 4 evaluates to 3. The modulo operator computes the remainder: 14 % 4 evaluates to 2. Thus, c = 3 + 2 = 5.",
            "trace": "a = 14, b = 4\na / b = 14 / 4 = 3\na % b = 14 % 4 = 2\nc = 3 + 2 = 5",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 3 + 2 = 5.",
                "B": "Incorrectly ignored the modulo result (14 % 4 = 2).",
                "C": "Mistakenly performed floating-point division (14 / 4 = 3.5 + 2 = 5.5). Integer variables truncate fractions.",
                "D": "Calculation error in division or remainder."
            },
            "placement_trap": "Assuming division yields a floating point value (3.5) instead of truncating to an integer (3).",
            "real_world_application": "Distributing items into equal-sized batches and finding leftover items.",
            "placement_tip": "Whenever variables are declared as Integer, integer division always discards the fractional part.",
            "source_type": "Common Placement Pattern",
            "source_note": "Classic Accenture & Capgemini integer arithmetic question pattern."
        },
        {
            "id": 2,
            "question": "What is the final value of variable 'res' after executing the pseudocode?",
            "pseudocode": "Integer x, y, res\nSet x = 12, y = 5\nSet res = x + y * 2 - 8 / 4\nPrint res",
            "question_type": "Output Prediction",
            "topic": "Programming Fundamentals",
            "concept": "Operator precedence and associativity",
            "difficulty": "Easy",
            "options": ["32", "20", "22", "18"],
            "correct_answer": "20",
            "correct_option_index": 1,
            "explanation": "Multiplication (*) and division (/) have higher precedence than addition (+) and subtraction (-), and evaluate from left to right. y * 2 = 5 * 2 = 10. 8 / 4 = 2. Then, x + 10 - 2 = 12 + 10 - 2 = 22 - 2 = 20.",
            "trace": "Step 1: y * 2 = 5 * 2 = 10\nStep 2: 8 / 4 = 2\nStep 3: 12 + 10 = 22\nStep 4: 22 - 2 = 20",
            "why_other_options_are_wrong": {
                "A": "Evaluated strictly left-to-right without precedence: (12 + 5) * 2 - 8 / 4 = 32.",
                "B": "Correct answer: Multiplication and division happen before addition and subtraction.",
                "C": "Forgot to subtract 8 / 4 = 2 at the end.",
                "D": "Miscalculated 12 + 10 - 2."
            },
            "placement_trap": "Evaluating operators strictly from left-to-right rather than following standard BODMAS/operator precedence.",
            "real_world_application": "Calculating total price with quantity multipliers and applied flat discounts.",
            "placement_tip": "Remember: *, /, % share the same high precedence level; +, - have lower precedence.",
            "source_type": "Reported Placement Pattern",
            "source_note": "Frequently tested in Cognizant GenC and TCS NQT aptitude rounds."
        },
        {
            "id": 3,
            "question": "What will be the output of the following pseudocode?",
            "pseudocode": "Integer p, q\nSet p = 7\nSet q = ++p + p++\nPrint p, q",
            "question_type": "Output Prediction",
            "topic": "Programming Fundamentals",
            "concept": "Pre-increment and post-increment operators",
            "difficulty": "Easy",
            "options": ["9, 16", "8, 16", "9, 15", "8, 15"],
            "correct_answer": "9, 16",
            "correct_option_index": 0,
            "explanation": "Initial p = 7. ++p is pre-increment: p becomes 8 immediately and evaluates to 8. Then p++ is post-increment: it uses current value 8 for the addition, then increments p to 9. Thus, q = 8 + 8 = 16, and final p = 9.",
            "trace": "p = 7\n++p -> p increments to 8, value used = 8\np++ -> value used = 8, p increments to 9\nq = 8 + 8 = 16\nfinal p = 9",
            "why_other_options_are_wrong": {
                "A": "Correct answer: p becomes 9, q evaluates to 8 + 8 = 16.",
                "B": "Forgot that post-increment p++ eventually increments p to 9.",
                "C": "Calculated q as 7 + 8 = 15.",
                "D": "Confused both pre and post increments."
            },
            "placement_trap": "Thinking post-increment changes the value before the expression evaluation.",
            "real_world_application": "Index pointers in buffer traversal where an item is fetched before moving to the next position.",
            "placement_tip": "Pre-increment: 'Change first, then use'. Post-increment: 'Use current value first, then change'.",
            "source_type": "Reported Placement Pattern",
            "source_note": "A staple in Accenture pseudocode rounds."
        },
        {
            "id": 4,
            "question": "What is printed when the following pseudocode executes?",
            "pseudocode": "Integer a, b\nSet a = 15, b = 25\nif (a > 10 AND b < 20)\n    Print a + b\nelse\n    Print a * 2\nEnd if",
            "question_type": "Output Prediction",
            "topic": "Conditional Statements",
            "concept": "Logical AND evaluation in conditional statement",
            "difficulty": "Easy",
            "options": ["40", "30", "50", "15"],
            "correct_answer": "30",
            "correct_option_index": 1,
            "explanation": "The condition tests (a > 10 AND b < 20). Here a = 15 > 10 is TRUE, but b = 25 < 20 is FALSE. Since TRUE AND FALSE evaluates to FALSE, the else branch executes: Print a * 2 = 15 * 2 = 30.",
            "trace": "a = 15, b = 25\nCondition: (15 > 10) AND (25 < 20) -> TRUE AND FALSE -> FALSE\nExecute else block: 15 * 2 = 30",
            "why_other_options_are_wrong": {
                "A": "Falsely assumed the if-condition was true and computed 15 + 25 = 40.",
                "B": "Correct answer: condition is false, so else block outputs 30.",
                "C": "Arithmetic error (b * 2 instead of a * 2).",
                "D": "Printed 'a' directly without executing multiplication."
            },
            "placement_trap": "Overlooking that logical AND requires BOTH conditions to be true.",
            "real_world_application": "Security validation: User must be an adult AND pass background verification.",
            "placement_tip": "In an AND expression, the moment any sub-condition is false, the entire condition is false.",
            "source_type": "Concept-Based",
            "source_note": "Standard logical conditional test in TCS Ninja and Infosys."
        },
        {
            "id": 5,
            "question": "What will be the output of the following pseudocode?",
            "pseudocode": "Integer num, count\nSet num = 5, count = 0\nwhile (num > 0)\n    Set count = count + num\n    Set num = num - 2\nEnd while\nPrint count",
            "question_type": "Output Prediction",
            "topic": "Loops",
            "concept": "While loop execution with step decrement",
            "difficulty": "Easy",
            "options": ["9", "15", "8", "6"],
            "correct_answer": "9",
            "correct_option_index": 0,
            "explanation": "Iteration 1: num = 5 > 0 -> count = 0 + 5 = 5, num becomes 5 - 2 = 3.\nIteration 2: num = 3 > 0 -> count = 5 + 3 = 8, num becomes 3 - 2 = 1.\nIteration 3: num = 1 > 0 -> count = 8 + 1 = 9, num becomes 1 - 2 = -1.\nIteration 4: num = -1 > 0 is FALSE. Loop terminates. Output is 9.",
            "trace": "Iter 1: num=5, count=0+5=5, num=3\nIter 2: num=3, count=5+3=8, num=1\nIter 3: num=1, count=8+1=9, num=-1\nIter 4: num=-1 > 0 is FALSE. Terminate.\nOutput: 9",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 5 + 3 + 1 = 9.",
                "B": "Assumed step decrement was 1 (5 + 4 + 3 + 2 + 1 = 15).",
                "C": "Prematurely stopped before processing num = 1.",
                "D": "Miscalculated iteration sums."
            },
            "placement_trap": "Missing the step decrement of -2 instead of the standard -1.",
            "real_world_application": "Counting down battery depletion during intermittent bursts.",
            "placement_tip": "Always check the loop decrement/increment step size before calculating the running sum.",
            "source_type": "Reported Placement Pattern",
            "source_note": "Frequent loop tracing question in Capgemini."
        },
        {
            "id": 6,
            "question": "How many times will the message 'Hello' be printed?",
            "pseudocode": "Integer i\nfor (i = 1 to 10 step 3)\n    Print \"Hello\"\nEnd for",
            "question_type": "Logic Tracing",
            "topic": "Loops",
            "concept": "For loop iteration count with step size",
            "difficulty": "Easy",
            "options": ["4 times", "3 times", "10 times", "5 times"],
            "correct_answer": "4 times",
            "correct_option_index": 0,
            "explanation": "The loop starts at i = 1 and increments by 3 each iteration: i = 1 (1st), i = 4 (2nd), i = 7 (3rd), i = 10 (4th). On the next increment, i = 13 which exceeds the upper bound 10. Thus, 'Hello' is printed exactly 4 times.",
            "trace": "i = 1: prints Hello (count = 1)\ni = 4: prints Hello (count = 2)\ni = 7: prints Hello (count = 3)\ni = 10: prints Hello (count = 4)\ni = 13: 13 > 10 -> loop terminates",
            "why_other_options_are_wrong": {
                "A": "Correct answer: values of i are 1, 4, 7, 10 (4 iterations).",
                "B": "Assumed upper bound 10 was exclusive, missing i = 10.",
                "C": "Assumed default step of 1.",
                "D": "Miscounted the sequence."
            },
            "placement_trap": "Forgetting that 'for i = 1 to 10' is inclusive of the endpoint 10 in standard pseudocode.",
            "real_world_application": "Sampling sensor data every 3 seconds over a 10-second window.",
            "placement_tip": "Formula for inclusive loop iterations: floor((End - Start) / Step) + 1 = floor((10 - 1) / 3) + 1 = 3 + 1 = 4.",
            "source_type": "Common Placement Pattern",
            "source_note": "Commonly asked iteration counting pattern in Wipro and Cognizant."
        },
        {
            "id": 7,
            "question": "What is the value of arr[3] after executing the pseudocode?",
            "pseudocode": "Integer arr[5] = {10, 20, 30, 40, 50}\nSet arr[1] = arr[0] + arr[2]\nSet arr[3] = arr[1] - arr[4]\nPrint arr[3]",
            "question_type": "Array Tracing",
            "topic": "Arrays",
            "concept": "0-indexed array access and element updates",
            "difficulty": "Easy",
            "options": ["-10", "10", "-20", "20"],
            "correct_answer": "-10",
            "correct_option_index": 0,
            "explanation": "Initial array: arr[0]=10, arr[1]=20, arr[2]=30, arr[3]=40, arr[4]=50.\nLine 2 updates arr[1] = arr[0] + arr[2] = 10 + 30 = 40.\nLine 3 updates arr[3] = arr[1] - arr[4] = 40 - 50 = -10.",
            "trace": "arr[1] = 10 + 30 = 40\narr[3] = 40 - 50 = -10\nOutput = -10",
            "why_other_options_are_wrong": {
                "A": "Correct answer: updated arr[1] (40) minus arr[4] (50) is -10.",
                "B": "Computed 50 - 40 instead of 40 - 50.",
                "C": "Used original value of arr[1] (20) giving 20 - 50 = -30.",
                "D": "Sign error."
            },
            "placement_trap": "Using the original initial value of arr[1] instead of the newly updated value.",
            "real_world_application": "Running balance calculation in financial ledger arrays.",
            "placement_tip": "Always track array modifications sequentially; subsequent calculations use the updated element values.",
            "source_type": "Reported Placement Pattern",
            "source_note": "Direct array tracing pattern from Capgemini technical assessment."
        },
        {
            "id": 8,
            "question": "What will be the output of the bitwise operations in the pseudocode?",
            "pseudocode": "Integer a, b, c\nSet a = 6, b = 3\nSet c = (a & b) + (a | b)\nPrint c",
            "question_type": "Bitwise",
            "topic": "Bitwise",
            "concept": "Bitwise AND and bitwise OR operations",
            "difficulty": "Easy",
            "options": ["9", "7", "11", "5"],
            "correct_answer": "9",
            "correct_option_index": 0,
            "explanation": "In binary: a = 6 is 110_2, b = 3 is 011_2.\nBitwise AND (a & b): 110 & 011 = 010_2 = 2.\nBitwise OR (a | b): 110 | 011 = 111_2 = 7.\nSum c = 2 + 7 = 9.",
            "trace": "a = 6 = 0110 in binary\nb = 3 = 0011 in binary\na & b = 0010 = 2\na | b = 0111 = 7\nc = 2 + 7 = 9",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 2 + 7 = 9.",
                "B": "Only calculated bitwise OR (7) and dropped AND.",
                "C": "Computed arithmetic addition directly (6 + 3 + 2).",
                "D": "Calculation error in bitwise conversions."
            },
            "placement_trap": "Confusing bitwise AND/OR (&, |) with logical AND/OR (&&, ||).",
            "real_world_application": "Hardware register mask manipulation and flag settings.",
            "placement_tip": "Note the mathematical identity: (a & b) + (a | b) = a + b for any two integers! Here 6 + 3 = 9.",
            "source_type": "Reported PYQ",
            "source_note": "Reported in Accenture 2025-2026 pseudocode assessment."
        },
        {
            "id": 9,
            "question": "What is the final value of 'ans' after the conditional statement executes?",
            "pseudocode": "Integer m, n, ans\nSet m = 8, n = 12\nif (m < 5 OR n > 10)\n    Set ans = n - m\nelse\n    Set ans = m + n\nEnd if\nPrint ans",
            "question_type": "Output Prediction",
            "topic": "Conditional Statements",
            "concept": "Logical OR short-circuit and execution",
            "difficulty": "Easy",
            "options": ["4", "20", "8", "12"],
            "correct_answer": "4",
            "correct_option_index": 0,
            "explanation": "The condition is (m < 5 OR n > 10). m < 5 (8 < 5) is FALSE. However, n > 10 (12 > 10) is TRUE. Since FALSE OR TRUE evaluates to TRUE, the if branch executes: ans = n - m = 12 - 8 = 4.",
            "trace": "m = 8, n = 12\nCondition: (8 < 5) OR (12 > 10) -> FALSE OR TRUE -> TRUE\nans = 12 - 8 = 4",
            "why_other_options_are_wrong": {
                "A": "Correct answer: if-branch executes yielding 12 - 8 = 4.",
                "B": "Incorrectly assumed the condition was false and executed else branch (8 + 12 = 20).",
                "C": "Returned value of m.",
                "D": "Returned value of n."
            },
            "placement_trap": "Thinking OR requires both conditions to be true.",
            "real_world_application": "Access permission: allow entry if user is Admin OR has a VIP pass.",
            "placement_tip": "For logical OR, if at least ONE condition is true, the entire expression evaluates to true.",
            "source_type": "Concept-Based",
            "source_note": "Standard TCS Ninja / Wipro conditional MCQ."
        },
        {
            "id": 10,
            "question": "A system validates an employee bonus based on sales targets. What bonus is awarded?",
            "pseudocode": "Integer sales, bonus\nSet sales = 45000, bonus = 0\nif (sales >= 50000)\n    Set bonus = 5000\nelse if (sales >= 40000)\n    Set bonus = 3000\nelse\n    Set bonus = 1000\nEnd if\nPrint bonus",
            "question_type": "Scenario-Based",
            "topic": "Conditional Statements",
            "concept": "Multi-tier decision logic in business rules",
            "difficulty": "Easy",
            "options": ["3000", "5000", "1000", "0"],
            "correct_answer": "3000",
            "correct_option_index": 0,
            "explanation": "Sales = 45000. The first condition (45000 >= 50000) is FALSE. The program evaluates the next condition: (45000 >= 40000), which is TRUE. Therefore, bonus is set to 3000 and the ladder exits.",
            "trace": "sales = 45000\nCondition 1: 45000 >= 50000 is FALSE\nCondition 2: 45000 >= 40000 is TRUE\nbonus = 3000",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 45000 satisfies the tier >= 40000.",
                "B": "45000 does not meet the 50000 threshold.",
                "C": "The else branch is only taken if sales < 40000.",
                "D": "The initial value of bonus is overwritten by the matching branch."
            },
            "placement_trap": "Assuming multiple branches execute in an else-if ladder.",
            "real_world_application": "Corporate payroll bonus and commission calculations.",
            "placement_tip": "In an else-if ladder, as soon as one condition evaluates to true, its block executes and the rest of the ladder is skipped.",
            "source_type": "Expected 2026 Pattern",
            "source_note": "Campus placement scenario pattern for business logic."
        },
        {
            "id": 11,
            "question": "What will be the output of the following pseudocode?",
            "pseudocode": "Integer x, y\nSet x = 1\nfor (y = 1 to 4)\n    Set x = x * 2\nEnd for\nPrint x",
            "question_type": "Output Prediction",
            "topic": "Loops",
            "concept": "Accumulator multiplication in for loop",
            "difficulty": "Easy",
            "options": ["16", "8", "32", "12"],
            "correct_answer": "16",
            "correct_option_index": 0,
            "explanation": "Loop runs 4 times (for y = 1, 2, 3, 4).\ny = 1: x = 1 * 2 = 2\ny = 2: x = 2 * 2 = 4\ny = 3: x = 4 * 2 = 8\ny = 4: x = 8 * 2 = 16\nFinal output is 16.",
            "trace": "Start: x = 1\ny = 1: x = 2\ny = 2: x = 4\ny = 3: x = 8\ny = 4: x = 16\nResult = 16",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 2^4 = 16.",
                "B": "Stopped after 3 iterations (2^3 = 8).",
                "C": "Executed an extra 5th iteration (2^5 = 32).",
                "D": "Calculated addition instead of repeated multiplication."
            },
            "placement_trap": "Off-by-one counting of loop iterations (running 3 times instead of 4).",
            "real_world_application": "Computing powers of two for binary memory allocations.",
            "placement_tip": "A loop multiplying by 2 for N iterations computes Start * 2^N.",
            "source_type": "Common Placement Pattern",
            "source_note": "Standard loop accumulator question in Infosys and TCS."
        },
        {
            "id": 12,
            "question": "What is the output of the string character count pseudocode?",
            "pseudocode": "String str = \"PLACEMENT\"\nInteger count = 0, i\nfor (i = 0 to length(str) - 1)\n    if (str[i] == 'E')\n        Set count = count + 1\n    End if\nEnd for\nPrint count",
            "question_type": "String Tracing",
            "topic": "Strings",
            "concept": "Character traversal and frequency counting",
            "difficulty": "Easy",
            "options": ["2", "1", "3", "0"],
            "correct_answer": "2",
            "correct_option_index": 0,
            "explanation": "The string 'PLACEMENT' contains the characters: P, L, A, C, E, M, E, N, T. The letter 'E' appears at index 4 and index 6. Thus, count is incremented twice and outputs 2.",
            "trace": "Index 0: 'P' != 'E'\nIndex 1: 'L' != 'E'\nIndex 2: 'A' != 'E'\nIndex 3: 'C' != 'E'\nIndex 4: 'E' == 'E' -> count = 1\nIndex 5: 'M' != 'E'\nIndex 6: 'E' == 'E' -> count = 2\nIndex 7: 'N' != 'E'\nIndex 8: 'T' != 'E'\nTotal count = 2",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 'E' occurs twice in 'PLACEMENT'.",
                "B": "Only spotted the first 'E' at index 4.",
                "C": "Overcounted.",
                "D": "Assumed case mismatch or failed comparison."
            },
            "placement_trap": "Scanning quickly and missing the second 'E' near the end of the word.",
            "real_world_application": "Searching text documents for specific keyword or character frequencies.",
            "placement_tip": "Count characters methodically from index 0 to length - 1 without skipping.",
            "source_type": "Common Placement Pattern",
            "source_note": "Frequent string frequency pattern in Capgemini and Tech Mahindra."
        },
        {
            "id": 13,
            "question": "What will be the output of the function call?",
            "pseudocode": "Function addBonus(Integer base, Integer perf)\n    Integer total\n    Set total = base + perf * 100\n    Return total\nEnd Function\n\nInteger result\nSet result = addBonus(1000, 5)\nPrint result",
            "question_type": "Function Tracing",
            "topic": "Functions",
            "concept": "Function call by value and return values",
            "difficulty": "Easy",
            "options": ["1500", "1005", "5000", "15000"],
            "correct_answer": "1500",
            "correct_option_index": 0,
            "explanation": "The function receives base = 1000 and perf = 5. Inside the function: total = 1000 + (5 * 100) = 1000 + 500 = 1500. The function returns 1500 to 'result', which is printed.",
            "trace": "Calling addBonus(1000, 5)\nbase = 1000, perf = 5\nperf * 100 = 500\ntotal = 1000 + 500 = 1500\nReturn 1500",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 1000 + 500 = 1500.",
                "B": "Added perf without multiplying by 100.",
                "C": "Multiplied base * 5 instead.",
                "D": "Arithmetic scale error."
            },
            "placement_trap": "Adding base and perf before multiplying by 100 due to ignoring operator precedence.",
            "real_world_application": "Modular salary bonus calculation microservice.",
            "placement_tip": "Follow argument values strictly into parameters in the order they are passed.",
            "source_type": "Concept-Based",
            "source_note": "Foundational function parameter passing in Wipro and Cognizant."
        },
        {
            "id": 14,
            "question": "Identify the logical error in the pseudocode intended to find if an integer 'n' is even.",
            "pseudocode": "// Intended: Check if n is even\nif (n / 2 == 0)\n    Print \"Even\"\nelse\n    Print \"Odd\"\nEnd if",
            "question_type": "Debugging",
            "topic": "Debugging",
            "concept": "Using division instead of modulo for parity check",
            "difficulty": "Easy",
            "options": [
                "Division operator (/) is used instead of modulo operator (%)",
                "Comparison operator (==) should be assignment (=)",
                "The else statement is missing a condition",
                "The variable n must be floating point"
            ],
            "correct_answer": "Division operator (/) is used instead of modulo operator (%)",
            "correct_option_index": 0,
            "explanation": "To check if a number is even, we must test whether the remainder when divided by 2 is zero, which requires the modulo operator (n % 2 == 0). The division operator (n / 2) computes the quotient, which is only 0 when n is 0 or 1.",
            "trace": "For n = 4:\nIncorrect code: 4 / 2 = 2 == 0 is FALSE -> prints 'Odd' (BUG!)\nCorrect code: 4 % 2 = 0 == 0 is TRUE -> prints 'Even'",
            "why_other_options_are_wrong": {
                "A": "Correct answer: modulo (%) is the correct operator for checking remainders.",
                "B": "Comparison (==) is required in conditional statements; assignment (=) would be a syntax error.",
                "C": "The else statement naturally handles all non-matching cases.",
                "D": "Parity checks apply strictly to integers."
            },
            "placement_trap": "Confusing the quotient operator (/) with the remainder operator (%).",
            "real_world_application": "Alternating row colors in UI tables and load balancing between two servers.",
            "placement_tip": "Even/Odd tests always require checking remainder using n % 2 == 0.",
            "source_type": "Common Placement Pattern",
            "source_note": "Classic debugging MCQ in Capgemini and Accenture."
        },
        {
            "id": 15,
            "question": "What is the output of the following do-while loop?",
            "pseudocode": "Integer k = 10\ndo\n    Print k\n    Set k = k + 5\nwhile (k < 10)",
            "question_type": "Output Prediction",
            "topic": "Loops",
            "concept": "Do-while loop exit-controlled execution",
            "difficulty": "Easy",
            "options": ["10", "No output", "10 15", "Infinite loop"],
            "correct_answer": "10",
            "correct_option_index": 0,
            "explanation": "A do-while loop is an exit-controlled loop, meaning the body executes at least once before the condition is checked. 10 is printed, k becomes 15. The condition (15 < 10) is FALSE, so the loop terminates immediately.",
            "trace": "Initial: k = 10\nBody executes:\n  Print 10\n  k = 10 + 5 = 15\nCheck condition: (15 < 10) is FALSE\nLoop ends. Output: 10",
            "why_other_options_are_wrong": {
                "A": "Correct answer: prints 10 once because condition is tested at the end.",
                "B": "Treated the loop as an entry-controlled while loop.",
                "C": "Assumed second iteration ran before terminating.",
                "D": "Condition is false after first iteration, so no infinite loop occurs."
            },
            "placement_trap": "Assuming do-while behaves like a standard while loop and checks the condition before the first iteration.",
            "real_world_application": "Displaying a menu at least once before asking if user wants to repeat.",
            "placement_tip": "A do-while loop ALWAYS executes its body at least once regardless of whether the condition is true or false.",
            "source_type": "Common Placement Pattern",
            "source_note": "Reported in TCS and Infosys technical assessments."
        },
        {
            "id": 16,
            "question": "What will be printed by the following pseudocode?",
            "pseudocode": "Integer a = 5, b = 2\nSet a = a ^ b\nSet b = a ^ b\nSet a = a ^ b\nPrint a, b",
            "question_type": "Bitwise",
            "topic": "Bitwise",
            "concept": "XOR-based variable swapping without temporary variable",
            "difficulty": "Easy",
            "options": ["2, 5", "5, 2", "7, 7", "0, 0"],
            "correct_answer": "2, 5",
            "correct_option_index": 0,
            "explanation": "This is the classic bitwise XOR swap algorithm. Initial: a = 5 (101_2), b = 2 (010_2).\nLine 1: a = 5 ^ 2 = 7 (111_2)\nLine 2: b = 7 ^ 2 = 5 (101_2)\nLine 3: a = 7 ^ 5 = 2 (010_2)\nFinal values: a = 2, b = 5 (values are swapped!).",
            "trace": "a = 5, b = 2\n1) a = 5 ^ 2 = 7\n2) b = 7 ^ 2 = 5\n3) a = 7 ^ 5 = 2\nOutput: 2, 5",
            "why_other_options_are_wrong": {
                "A": "Correct answer: values of a and b have swapped.",
                "B": "Original unswapped values.",
                "C": "Miscalculated XOR as addition.",
                "D": "Thought XOR cancelled everything out."
            },
            "placement_trap": "Failing to recognize the 3-line XOR swap idiom.",
            "real_world_application": "In-place memory-efficient value swapping in embedded systems.",
            "placement_tip": "The sequence 'a = a^b; b = a^b; a = a^b' always swaps the values of a and b.",
            "source_type": "Reported PYQ",
            "source_note": "Repeatedly reported in Accenture and Capgemini pseudocode rounds."
        },
        {
            "id": 17,
            "question": "What is the output of the following pseudocode?",
            "pseudocode": "Integer x = 0\nfor (Integer i = 1 to 5)\n    if (i == 3)\n        continue\n    End if\n    Set x = x + i\nEnd for\nPrint x",
            "question_type": "Output Prediction",
            "topic": "Loops",
            "concept": "Continue statement in for loop",
            "difficulty": "Easy",
            "options": ["12", "15", "3", "10"],
            "correct_answer": "12",
            "correct_option_index": 0,
            "explanation": "The loop runs for i = 1, 2, 3, 4, 5. When i = 3, the continue statement executes, skipping the rest of the loop body for that iteration. Thus x accumulates 1 + 2 + 4 + 5 = 12 (3 is skipped).",
            "trace": "i=1: x = 0 + 1 = 1\ni=2: x = 1 + 2 = 3\ni=3: continue (x remains 3)\ni=4: x = 3 + 4 = 7\ni=5: x = 7 + 5 = 12\nFinal x = 12",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 1 + 2 + 4 + 5 = 12.",
                "B": "Included 3 (1+2+3+4+5 = 15), ignoring the continue statement.",
                "C": "Confused continue with break (stopping at i=3).",
                "D": "Calculation error."
            },
            "placement_trap": "Confusing 'continue' (skips rest of current iteration) with 'break' (terminates entire loop).",
            "real_world_application": "Filtering out invalid or corrupted sensor records in a data pipeline.",
            "placement_tip": "Continue skips only the CURRENT iteration; the loop moves directly to the next value of i.",
            "source_type": "Reported Placement Pattern",
            "source_note": "A frequent question pattern in TCS and Cognizant."
        },
        {
            "id": 18,
            "question": "What will be printed when this pseudocode executes?",
            "pseudocode": "Integer sum = 0, i\nfor (i = 1 to 5)\n    if (i == 3)\n        break\n    End if\n    Set sum = sum + i\nEnd for\nPrint sum",
            "question_type": "Output Prediction",
            "topic": "Loops",
            "concept": "Break statement loop termination",
            "difficulty": "Easy",
            "options": ["3", "12", "15", "6"],
            "correct_answer": "3",
            "correct_option_index": 0,
            "explanation": "i = 1: sum = 0 + 1 = 1\ni = 2: sum = 1 + 2 = 3\ni = 3: i == 3 is true -> break executes, terminating the loop completely.\nThe loop stops, and sum = 3 is printed.",
            "trace": "i = 1: sum = 1\ni = 2: sum = 3\ni = 3: break terminates loop!\nPrint sum -> 3",
            "why_other_options_are_wrong": {
                "A": "Correct answer: loop terminated at i = 3 after accumulating 1 + 2 = 3.",
                "B": "Treated break as continue (skipping only 3 yielding 12).",
                "C": "Ignored break completely (sum 1 to 5 = 15).",
                "D": "Added 3 before breaking."
            },
            "placement_trap": "Treating break like continue, or assuming break happens after the body executes.",
            "real_world_application": "Early exit when a target item is found during a linear search.",
            "placement_tip": "Break immediately terminates the innermost enclosing loop.",
            "source_type": "Common Placement Pattern",
            "source_note": "Core break vs continue comparison in Capgemini."
        },
        {
            "id": 19,
            "question": "What is the final value of 'val'?",
            "pseudocode": "Integer val = 20\nSet val = val >> 2\nPrint val",
            "question_type": "Bitwise",
            "topic": "Bitwise",
            "concept": "Bitwise right shift operator",
            "difficulty": "Easy",
            "options": ["5", "10", "80", "4"],
            "correct_answer": "5",
            "correct_option_index": 0,
            "explanation": "The right shift operator (val >> k) shifts bits to the right by k positions, effectively dividing the integer by 2^k using integer division. Here, 20 >> 2 = floor(20 / 2^2) = floor(20 / 4) = 5. In binary: 20 is 10100_2. Shift right by 2 bits gives 101_2 = 5.",
            "trace": "20 in binary: 0001 0100\nShift right by 2: 0000 0101 = 5\nAlternatively: 20 / 4 = 5",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 20 >> 2 = 5.",
                "B": "Only shifted right by 1 bit (20 / 2 = 10).",
                "C": "Left shifted instead of right shifted (20 * 4 = 80).",
                "D": "Arithmetic error."
            },
            "placement_trap": "Confusing left shift (<<) which multiplies by 2, with right shift (>>) which divides by 2.",
            "real_world_application": "Fast integer division by powers of 2 in performance-critical graphics code.",
            "placement_tip": "Formula: x >> k equals floor(x / 2^k). x << k equals x * 2^k.",
            "source_type": "Reported PYQ",
            "source_note": "Reported in Accenture pseudocode rounds."
        },
        {
            "id": 20,
            "question": "What will be the output of the array traversal?",
            "pseudocode": "Integer arr[4] = {3, 7, 2, 9}\nInteger max = arr[0], i\nfor (i = 1 to 3)\n    if (arr[i] > max)\n        Set max = arr[i]\n    End if\nEnd for\nPrint max",
            "question_type": "Array Tracing",
            "topic": "Arrays",
            "concept": "Finding the maximum element in an array",
            "difficulty": "Easy",
            "options": ["9", "7", "3", "21"],
            "correct_answer": "9",
            "correct_option_index": 0,
            "explanation": "Initial max = arr[0] = 3.\ni = 1: arr[1] = 7 > 3 -> max becomes 7.\ni = 2: arr[2] = 2 > 7 is False -> max remains 7.\ni = 3: arr[3] = 9 > 7 -> max becomes 9.\nLoop terminates. Output is 9.",
            "trace": "max = 3\ni=1: 7 > 3 -> max = 7\ni=2: 2 > 7 -> false\ni=3: 9 > 7 -> max = 9\nOutput: 9",
            "why_other_options_are_wrong": {
                "A": "Correct answer: maximum element is 9.",
                "B": "Stopped early before inspecting index 3.",
                "C": "Original starting element.",
                "D": "Sum of all elements instead of maximum."
            },
            "placement_trap": "Confusing array sum with finding the maximum element.",
            "real_world_application": "Finding the highest test score in a student database.",
            "placement_tip": "Standard maximum search initializes max with the first element and updates whenever a larger element is found.",
            "source_type": "Common Placement Pattern",
            "source_note": "Standard array algorithm in TCS and Infosys."
        },
        {
            "id": 21,
            "question": "A login system allows up to 3 attempts. What message is printed if the user enters wrong credentials 3 times?",
            "pseudocode": "Integer attempts = 0\nBoolean loginSuccess = False\nwhile (attempts < 3 AND loginSuccess == False)\n    Set attempts = attempts + 1\nEnd while\nif (loginSuccess == True)\n    Print \"Welcome\"\nelse\n    Print \"Account Locked\"\nEnd if",
            "question_type": "Scenario-Based",
            "topic": "Conditional Statements",
            "concept": "Flag and counter controlled authentication loop",
            "difficulty": "Easy",
            "options": ["Account Locked", "Welcome", "No output", "Infinite loop"],
            "correct_answer": "Account Locked",
            "correct_option_index": 0,
            "explanation": "Attempts increments 1, 2, 3 while loginSuccess remains False. When attempts reaches 3, the condition (attempts < 3) becomes False, exiting the loop. Since loginSuccess is still False, the else block executes and prints 'Account Locked'.",
            "trace": "attempts=0, loginSuccess=False\nIter 1: attempts=1\nIter 2: attempts=2\nIter 3: attempts=3\nLoop condition (3 < 3) is False. Exit.\nloginSuccess == True is False -> else block executes.\nPrint: Account Locked",
            "why_other_options_are_wrong": {
                "A": "Correct answer: loop ends after 3 attempts with loginSuccess still False.",
                "B": "loginSuccess was never set to True.",
                "C": "The else block guarantees an output.",
                "D": "The loop terminates cleanly when attempts reaches 3."
            },
            "placement_trap": "Assuming attempts can increment indefinitely.",
            "real_world_application": "Bank portal brute-force login lockout mechanism.",
            "placement_tip": "Trace both the counter and the Boolean flag condition to determine when the loop breaks.",
            "source_type": "Expected 2026 Pattern",
            "source_note": "Realistic security scenario pattern for 2026 assessments."
        },
        {
            "id": 22,
            "question": "What is the value of 'count' after checking divisibility by 3?",
            "pseudocode": "Integer count = 0, i\nfor (i = 1 to 10)\n    if (i % 3 == 0)\n        Set count = count + 1\n    End if\nEnd for\nPrint count",
            "question_type": "Output Prediction",
            "topic": "Loops",
            "concept": "Counting multiples using modulo condition",
            "difficulty": "Easy",
            "options": ["3", "4", "2", "10"],
            "correct_answer": "3",
            "correct_option_index": 0,
            "explanation": "The loop checks numbers 1 to 10 for divisibility by 3. Multiples of 3 in this range are 3, 6, and 9. That is exactly 3 numbers, so count is incremented 3 times and prints 3.",
            "trace": "i = 3: 3 % 3 == 0 -> count = 1\ni = 6: 6 % 3 == 0 -> count = 2\ni = 9: 9 % 3 == 0 -> count = 3\nOther numbers leave non-zero remainder.\nFinal count = 3",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 3, 6, 9 are the 3 multiples of 3 in 1..10.",
                "B": "Overcounted by including 10 or 0.",
                "C": "Missed one of the multiples.",
                "D": "Total number of iterations instead of matching count."
            },
            "placement_trap": "Counting 10 as divisible by 3.",
            "real_world_application": "Filtering items for promotional offers every 3rd transaction.",
            "placement_tip": "Number of multiples of k up to N is floor(N / k) = floor(10 / 3) = 3.",
            "source_type": "Common Placement Pattern",
            "source_note": "Standard modulo counter pattern in Accenture and Wipro."
        },
        {
            "id": 23,
            "question": "What is the output of the nested conditional statement?",
            "pseudocode": "Integer age = 20, weight = 55\nif (age >= 18)\n    if (weight >= 50)\n        Print \"Eligible to Donate\"\n    else\n        Print \"Underweight\"\n    End if\nelse\n    Print \"Underage\"\nEnd if",
            "question_type": "Output Prediction",
            "topic": "Conditional Statements",
            "concept": "Nested if-else logic",
            "difficulty": "Easy",
            "options": ["Eligible to Donate", "Underweight", "Underage", "No output"],
            "correct_answer": "Eligible to Donate",
            "correct_option_index": 0,
            "explanation": "Outer condition: age (20) >= 18 is TRUE. Code enters outer block.\nInner condition: weight (55) >= 50 is TRUE. Executes inner if block: prints 'Eligible to Donate'.",
            "trace": "age = 20 >= 18 -> TRUE (enter)\nweight = 55 >= 50 -> TRUE\nPrint: Eligible to Donate",
            "why_other_options_are_wrong": {
                "A": "Correct answer: both conditions pass.",
                "B": "Weight is 55, which is >= 50.",
                "C": "Age is 20, which is >= 18.",
                "D": "One branch must always execute."
            },
            "placement_trap": "Mixing up the inner else branch with the outer else branch.",
            "real_world_application": "Blood bank donation eligibility verification criteria.",
            "placement_tip": "Trace nested conditions from outside-in: the inner condition is tested only if the outer condition is true.",
            "source_type": "Concept-Based",
            "source_note": "Common nested logic test in Cognizant and TCS."
        },
        {
            "id": 24,
            "question": "What will be the output of the following pseudocode?",
            "pseudocode": "Integer a = 10, b = 20\nSet a = a + b\nSet b = a - b\nSet a = a - b\nPrint a, b",
            "question_type": "Logic Tracing",
            "topic": "Programming Fundamentals",
            "concept": "Arithmetic swapping without a third variable",
            "difficulty": "Easy",
            "options": ["20, 10", "10, 20", "30, 30", "0, 0"],
            "correct_answer": "20, 10",
            "correct_option_index": 0,
            "explanation": "This is the arithmetic variable swap algorithm:\nLine 1: a = 10 + 20 = 30\nLine 2: b = 30 - 20 = 10 (b now has initial a)\nLine 3: a = 30 - 10 = 20 (a now has initial b)\nFinal result: a = 20, b = 10.",
            "trace": "Start: a = 10, b = 20\n1) a = 10 + 20 = 30\n2) b = 30 - 20 = 10\n3) a = 30 - 10 = 20\nOutput: 20, 10",
            "why_other_options_are_wrong": {
                "A": "Correct answer: variables are swapped.",
                "B": "Original unswapped state.",
                "C": "Assumed variables retain the sum 30.",
                "D": "Miscalculated subtractions."
            },
            "placement_trap": "Assuming the values will be corrupted or lost without a temp variable.",
            "real_world_application": "Swapping register contents in memory-constrained microcontrollers.",
            "placement_tip": "The sequence 'a = a+b; b = a-b; a = a-b' swaps the two numbers.",
            "source_type": "Common Placement Pattern",
            "source_note": "Classic aptitude question across all service MNCs."
        },
        {
            "id": 25,
            "question": "What is the output of the loop when the step is negative?",
            "pseudocode": "Integer s = 0, j\nfor (j = 5 down to 1 step 2)\n    Set s = s + j\nEnd for\nPrint s",
            "question_type": "Output Prediction",
            "topic": "Loops",
            "concept": "Reverse loop with step decrement",
            "difficulty": "Easy",
            "options": ["9", "15", "8", "6"],
            "correct_answer": "9",
            "correct_option_index": 0,
            "explanation": "The loop starts at j = 5 and decrements by 2 each step: j = 5, then j = 3, then j = 1. Next step would be -1 which is below 1. Thus, s = 5 + 3 + 1 = 9.",
            "trace": "j = 5: s = 0 + 5 = 5\nj = 3: s = 5 + 3 = 8\nj = 1: s = 8 + 1 = 9\nj = -1: loop ends\nOutput: 9",
            "why_other_options_are_wrong": {
                "A": "Correct answer: 5 + 3 + 1 = 9.",
                "B": "Assumed step 1 (5+4+3+2+1 = 15).",
                "C": "Stopped at j = 3.",
                "D": "Calculated 5 + 1."
            },
            "placement_trap": "Forgetting that a step of 2 in reverse skips even numbers.",
            "real_world_application": "Reverse countdown timer with periodic step intervals.",
            "placement_tip": "Always write down the explicit sequence of loop variable values: 5, 3, 1.",
            "source_type": "Common Placement Pattern",
            "source_note": "Frequent reverse loop question in Capgemini and Tech Mahindra."
        }
    ]
